version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: WebAppChat2
      POSTGRES_USER: hau
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
